// <auto-generated />
using System;
using AmfValor.AmfMoney.PortalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmfValor.AmfMoney.PortalApi.Migrations
{
    [DbContext(typeof(AmfMoneyContext))]
    [Migration("20190702180310_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AmfValor.AmfMoney.PortalApi.Data.Model.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birth");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<byte[]>("PinHashed")
                        .IsRequired();

                    b.Property<byte[]>("PinSalt")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AmfValor.AmfMoney.PortalApi.Model.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("StopGain")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TradingBookId");

                    b.HasKey("Id");

                    b.HasIndex("TradingBookId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("AmfValor.AmfMoney.PortalApi.Model.TradingBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("TradingBooks");
                });

            modelBuilder.Entity("AmfValor.AmfMoney.PortalApi.Model.Trade", b =>
                {
                    b.HasOne("AmfValor.AmfMoney.PortalApi.Model.TradingBook")
                        .WithMany("Trades")
                        .HasForeignKey("TradingBookId");
                });

            modelBuilder.Entity("AmfValor.AmfMoney.PortalApi.Model.TradingBook", b =>
                {
                    b.OwnsOne("AmfValor.AmfMoney.PortalApi.Model.TradingBookSetting", "Setting", b1 =>
                        {
                            b1.Property<int>("TradingBookId");

                            b1.Property<decimal>("AmountPerCaptal")
                                .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                                .HasColumnName("AmountPerCaptal")
                                .HasColumnType("decimal(2,2)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnName("Name")
                                .HasColumnType("varchar(50)");

                            b1.Property<decimal>("RiskPerTrade")
                                .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                                .HasColumnName("RiskPerTrade")
                                .HasColumnType("decimal(2,2)");

                            b1.Property<sbyte>("RiskRewardRatio")
                                .HasColumnName("RiskRewardRatio")
                                .HasColumnType("tinyint(1)");

                            b1.Property<decimal>("TotalCaptal")
                                .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                                .HasColumnName("TotalCaptal")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("TradingBookId");

                            b1.ToTable("TradingBooks");

                            b1.HasOne("AmfValor.AmfMoney.PortalApi.Model.TradingBook")
                                .WithOne("Setting")
                                .HasForeignKey("AmfValor.AmfMoney.PortalApi.Model.TradingBookSetting", "TradingBookId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
